# Deploy from tyr-infra folder / app.
# App name example: tyr-infra_pgadmin.

networks:
  typingrealm: # For legacy apps: FoulBot/KartMan.
    name: typingrealm
    external: true
  proxy:
    name: tyr-net-proxy
    external: true
  prod-proxy:
    name: tyr-prod-net-proxy
    external: true
  dev-proxy:
    name: tyr-dev-net-proxy
    external: true
  prod-infra: # Used to send logs from services to infra / etc.
    name: tyr-prod-net-infrastructure
    external: true
  dev-infra:
    name: tyr-dev-net-infrastructure
    external: true
  prod-admin: # Used to administer services using tools like pgadmin.
    name: tyr-prod-net-administration
    external: true
  dev-admin:
    name: tyr-dev-net-administration
    external: true

services:
  caddy:
    image: caddy
    ports:
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
    volumes:
      - /data/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /data/caddy/data:/data
    restart: unless-stopped
    networks:
      - typingrealm
      - proxy
      - prod-proxy
      - dev-proxy
    healthcheck:
      test: wget --spider http://localhost/health || exit 1
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 100m
      placement:
        constraints:
          - node.labels.tyr-prod-infra==true

  pgadmin: # Required to run as 5050 user.
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=ewancoder@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=qwerty123
    volumes:
      - /data/tyr/infra/pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    networks:
      - proxy
      - prod-admin
      - dev-admin
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://localhost || exit 1"]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 200m
      placement:
        constraints:
          - node.labels.tyr-dev-infra==true

  seq:
    image: datalust/seq
    user: 2000:2000
    environment:
      - ACCEPT_EULA=Y
      - SEQ_API_CANONICALURI=https://seq.typingrealm.com
      - SEQ_FIRSTRUN_ADMINPASSWORD=qwerty123
    volumes:
      - /data/tyr/infra/seq:/data
    restart: unless-stopped
    ports:
      - 5341:5341 # For FoulBot/KartMan, remove later.
    networks:
      typingrealm: # For FoulBot/KartMan, remove later.
        aliases:
          - seq
      proxy:
        aliases:
          - seq
      prod-infra:
        aliases:
          - tyr-prod-infra_seq
      dev-infra:
        aliases:
          - tyr-dev-infra_seq
    healthcheck:
      test: ["CMD-SHELL", "ps aux | grep /seqsvr/Seq | grep -v grep || exit 1"]
    deploy:
      resources:
        limits:
          memory: 20G
        reservations:
          memory: 2G
      placement:
        constraints:
          - node.labels.tyr-dev-infra==true

  redisinsight:
    image: redis/redisinsight:latest
    user: 2000:2000
    volumes:
      - /data/tyr/infra/redisinsight:/data
    restart: unless-stopped
    networks:
      - proxy
      - prod-admin
      - dev-admin
    healthcheck:
      test: ["CMD-SHELL", "wget --spider http://127.0.0.1:5540 || exit 1"]
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 200m
      placement:
        constraints:
          - node.labels.tyr-dev-infra==true

  # Production cross-service cache
  prod-cache:
    image: valkey/valkey
    user: 2000:2000
    volumes:
      - /data/tyr/prod/infra/cache:/data
    command: valkey-server --appendonly yes --save 60 1 --dir /data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      prod-infra:
        aliases:
          - tyr-prod-infra_cache
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 100m
      placement:
        constraints:
          - node.labels.tyr-prod-infra==true

  # TODO: Add ports for local development & 'internet' network.
  # Development cross-service cache
  dev-cache:
    image: valkey/valkey
    user: 2000:2000
    volumes:
      - /data/tyr/dev/infra/cache:/data
    command: valkey-server --appendonly yes --save 60 1 --dir /data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      dev-infra:
        aliases:
          - tyr-dev-infra_cache
      dev-admin:
        aliases:
          - tyr-dev-admin_cache
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 100m
      placement:
        constraints:
          - node.labels.tyr-dev-infra==true
